name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install jq
        run: sudo apt-get install jq
      - name: Update README
        run: |
          PULL_REQUESTS=$(curl -s https://api.github.com/users/Jayanta7022/events | jq '[.[] | select(.type=="PullRequestEvent")]')
          echo "<!--START_SECTION:contributions-->" > temp.md
          echo "$PULL_REQUESTS" >> temp.md
          echo "<!--END_SECTION:contributions-->" >> temp.md
          sed -i '/<!--START_SECTION:contributions-->/, /<!--END_SECTION:contributions-->/ {r temp.md' README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest contributions' || exit 0
          git push
